<script>
    jQuery(function(){
        jQuery('#slides').slides({
            preload: true,
            preloadImage: '<?php echo $this->getSkinUrl('images/carousel/loading.gif') ?>',
            play: 5000,
            pause: 2500,
            hoverPause: true,
            animationStart: function(current){
                jQuery('.caption').animate({
                    bottom:-35
                },100);
                if (window.console && console.log) {
                    // example return of current slide number
                    console.log('animationStart on slide: ', current);
                };
            },
            animationComplete: function(current){
                jQuery('.caption').animate({
                    bottom:0
                },200);
                if (window.console && console.log) {
                    // example return of current slide number
                    console.log('animationComplete on slide: ', current);
                };
            },
            slidesLoaded: function() {
                jQuery('.caption').animate({
                    bottom:0
                },200);
            }
        });
    });
</script>
</head>
<body>
    <div id="container">
        <div id="example">
            <img src="<?php echo $this->getSkinUrl('images/carousel/new-ribbon.png') ?>" width="112" height="112" alt="New Ribbon" id="ribbon">
            <div id="slides">
                <div class="slides_container">
                    <?php $images = Mage::getModel('carousel/data')->getImage(); ?>
                    <?php if ((count($images) > 0)): ?>
                        <?php foreach ($images as $image) { ?>
                            <div class="slide">
                                <a href="http://www.flickr.com/photos/jliba/4665625073/" title="<?php echo $image->getTitle();?>" target="_blank"><img src="<?php echo Mage::getBaseUrl('media').$image->getImageSrc();?>" width="570" height="270" alt="<?php echo $image->getImageAltText(); ?>"></a>
                                <div class="caption" style="bottom:0">
                                    <p><?php echo $image->getTitle();?></p>
                                </div>
                            </div>
                        <?php } ?>
                    <?php endif; ?>
                </div>
                <a href="#" class="prev"><img src="<?php echo $this->getSkinUrl('images/carousel/arrow-prev.png') ?>" width="24" height="43" alt="Arrow Prev"></a>
                <a href="#" class="next"><img src="<?php echo $this->getSkinUrl('images/carousel/arrow-next.png') ?>" width="24" height="43" alt="Arrow Next"></a>
            </div>
            <img src="<?php echo $this->getSkinUrl('images/carousel/example-frame.png') ?>" width="739" height="341" alt="Example Frame" id="frame">
        </div>
        <div id="footer">
            <p>For full instructions go to <a href="http://slidesjs.com" target="_blank">http://slidesjs.com</a>.</p>
            <p>Slider design by Orman Clark at <a href="http://www.premiumpixels.com/" target="_blank">Premium Pixels</a>. You can donwload the source PSD at <a href="http://www.premiumpixels.com/clean-simple-image-slider-psd/" target="_blank">Premium Pixels</a></p>
            <p>&copy; 2010 <a href="http://nathansearles.com" target="_blank">Nathan Searles</a>. All rights reserved. Slides is licensed under the <a href="http://www.apache.org/licenses/LICENSE-2.0" target="_blank">Apache license</a>.</p>
        </div>
    </div>
